Algoritmo "pares_consecutivos"

Var
  x, soma : inteiro


Inicio
     escreva("Digite um Numero inteiro: ")
     leia(x)
     
     enquanto X <> 0 faca
     
     
        se X % 2 <> 0 entao
           x <- X + 1
        fimse

        soma <- 5 * X + 20
        escreval("SOMA= ", soma)
        
        escreva("Digite um Numero inteiro: ")
     leia(x)
        
     fimenquanto

Fimalgoritmo
